global:
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus-grafana
  scrape_interval: 25s
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.24.5:3000
