#Vagrant
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

#Prometheus
  config.vm.define "prometheus" do |prom|
    prom.vm.provider "virtualbox" do |n|
        n.name = "Ubuntu-Prometheus"
    end
    prom.vm.network "public_network"
    prom.vm.network "forwarded_port", guest: 3000, host: 3000
    prom.vm.network "forwarded_port", guest: 9090, host: 9090
    prom.vm.synced_folder "./docker-compose/prometheus", "/opt/prometheus/"
    prom.vm.synced_folder "./docker-compose/grafana", "/opt/grafana/"
    prom.vm.synced_folder "./ansible/", "/ansible/"
    prom.vm.provision "shell", path: "install.sh"
    prom.vm.provision "shell", inline: "ansible-playbook /ansible/playbook.yml"
  end
end